---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: reporting.input.pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /input
    type: ""
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    name: reporting.input.pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: reporting.output.pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /output
    type: ""
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    name: reporting.output.pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: reporting.log.pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /log
    type: ""
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    name: reporting.log.pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reporting.input.pvc
spec:
  volumeName: reporting.input.pv
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reporting.output.pvc
spec:
  volumeName: reporting.output.pv
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reporting.log.pvc
spec:
  volumeName: reporting.log.pvc
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: reporting
          imagePullPolicy: Never
          image: cotalent/reporting:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "10m"
          volumeMounts:
            - mountPath: "/var/systemA-reporting/input"
              name: reporting-input-local
            - mountPath: "/var/systemA-reporting/output"
              name: reporting-output-local
            - mountPath: "/var/log/reporting/"
              name: reporting-log-local
          ports:
            - name: http-port
              containerPort: 8080
      volumes:
        - name: reporting-input-local
          emptyDir: {}
        - name: reporting-output-local
          emptyDir: {}
        - name: reporting-log-local
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: reporting
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    app: jenkins
